basePath: /
consumes:
- application/json
definitions:
  enableMetricsResponse:
    type: object
    x-go-package: github.com/armosec/kubescape/v2/httphandler/docs
  getScanResultsResponse:
    properties:
      id:
        description: ID of the performed scan
        example: b211da07-ce6c-4cdd-9e81-7e7f40f170ea
        type: string
        x-go-name: ID
      response:
        description: Response payload
        example:
          message: Still busy.
        type: object
        x-go-name: Response
      type:
        description: Type of the response
        example: busy
        type: string
        x-go-name: Type
    type: object
    x-go-package: github.com/armosec/kubescape/v2/httphandler/docs
  triggerScanParams:
    properties:
      account:
        description: |-
          A Kubescape account ID to use for scanning.

          Same as `kubescape scan --account`.
        example: NewGuid()
        type: string
        x-go-name: Account
      excludedNamespaces:
        description: List of namespaces to exclude. Same as `kubescape scan --excluded-namespaces`
        example:
        - kube-system
        - armo-system
        items:
          type: string
        type: array
        x-go-name: ExcludedNamespaces
      format:
        default: json
        description: Results format. Same as `kubescape scan --format`
        example: json
        type: string
        x-go-name: Format
      hostScanner:
        description: Deploy Kubescape K8s host-scanner DeamonSet in the scanned cluster
          (same as `kubescape scan --enable-host-scan`)
        example: true
        type: boolean
        x-go-name: HostScanner
      includeNamespaces:
        description: List of namespaces to include. Same as `kubescape scan --include-namespaces`
        example:
        - litmus-tests
        - known-bad
        items:
          type: string
        type: array
        x-go-name: IncludeNamespaces
      keepLocal:
        description: |-
          Do not submit results to Kubescape Cloud.

          Same as `kubescape scan --keep-local`
        type: boolean
        x-go-name: KeepLocal
      submit:
        description: Submit results to Kubescape Cloud. Same as `kubescape scan --submit`.
        example: true
        type: boolean
        x-go-name: Submit
      targetNames:
        description: |-
          Name of the scan targets.

          For example, if you select `targetType: "framework"`, you can trigger a scan using the NSA and MITRE ATT&CK Framework by passing `targetNames: ["nsa, "mitre"]`.
        example:
        - nsa
        - mitre
        items:
          type: string
        type: array
        x-go-name: TargetNames
      targetType:
        description: |-
          Type of the scan target: either `framework` or `control`.
          framework Framework
          control Control
        enum:
        - framework
        - control
        example: framework
        type: string
        x-go-enum-desc: |-
          framework Framework
          control Control
        x-go-name: TargetType
      useCachedArtifacts:
        description: Use the cached artifacts instead of downloading (offline support)
        example: false
        type: boolean
        x-go-name: UseCachedArtifacts
    type: object
    x-go-package: github.com/armosec/kubescape/v2/httphandler/docs
  triggerScanResponse:
    properties:
      id:
        description: ID of the performed scan
        type: string
        x-go-name: Id
      response:
        description: Response payload as list of bytes
        type: object
        x-go-name: Response
      type:
        description: |-
          Type of the response object
          v1results V1Results
          busy Busy
          notBusy NotBusy
          ready Ready
          error Error
        enum:
        - v1results
        - busy
        - notBusy
        - ready
        - error
        type: string
        x-go-enum-desc: |-
          v1results V1Results
          busy Busy
          notBusy NotBusy
          ready Ready
          error Error
        x-go-name: Type
    type: object
    x-go-package: github.com/armosec/kubescape/v2/httphandler/docs
host: example.com
info:
  description: Documentation of our awesome API.
  title: kubescape_microservice
  version: 1.0.0
paths:
  /v1/metrics:
    post:
      description: Enables support for Prometheus metrics.
      operationId: enableMetrics
      responses:
        "200":
          $ref: '#/responses/enableMetricsResponse'
      summary: Trigger Kubescape support for Prometheus
      tags:
      - metrics
  /v1/results/{scanID}:
    get:
      operationId: getScanResults
      parameters:
      - description: ID of the previously performed scan
        in: path
        name: scanID
        required: true
        type: string
        x-go-name: ScanID
      responses:
        "200":
          $ref: '#/responses/getScanResultsResponse'
      summary: Read results of a previously performed scan.
      tags:
      - scanning
  /v1/scan:
    post:
      description: The server will return an ID and will execute the scanning asynchronously.
      operationId: triggerScan
      parameters:
      - description: Trigger scan parameters
        in: body
        name: Body
        schema:
          $ref: '#/definitions/triggerScanParams'
      - default: false
        description: |-
          Whether to wait for the result to complete.

          Triggers a synchronous scan. A synchronous scan returns the Scan results, and not a scan ID. Use synchronous scanning only in small clusters or with an increased timeout
        in: query
        name: wait
        type: boolean
        x-go-name: Wait
      - default: false
        description: Keep the results in local storage after returning.
        in: query
        name: keep
        type: boolean
        x-go-name: Keep
      responses:
        "200":
          $ref: '#/responses/triggerScanResponse'
      summary: Trigger a kubescape scan.
      tags:
      - scanning
produces:
- application/json
responses:
  enableMetricsResponse:
    description: ""
    schema:
      $ref: '#/definitions/enableMetricsResponse'
  getScanResultsResponse:
    description: ""
    schema:
      $ref: '#/definitions/getScanResultsResponse'
  triggerScanResponse:
    description: The triggerScan response object
    schema:
      $ref: '#/definitions/triggerScanResponse'
schemes:
- http
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
