name: pr-checks

on:
  pull_request:
    branches: [ master, dev ]
    types: [ edited, opened, synchronize, reopened ]
jobs:
  build:
    name: Create cross-platform build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install libgit2
        run: make libgit2
        if: matrix.os != 'windows-latest'

      # - name: Test cmd pkg
      #   run: cd cmd && go test -v ./...
      
      - name: Test core pkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go test -tags=static -v ./...

      - name: Test httphandler pkg
        run: cd httphandler && go test -tags=static -v ./...

      - name: Build
        env:
          RELEASE: v2.0.${{ github.run_number }} 
          CLIENT: test
          ArmoBEServer: api.armosec.io
          ArmoAuthServer: auth.armosec.io
          ArmoERServer: report.armo.cloud
          ArmoWebsite: cloud.armosec.io
          CGO_ENABLED: 1
        run: python3 --version && python3 build.py

      - name: Smoke Testing
        env:
          RELEASE: v2.0.${{ github.run_number }} 
          KUBESCAPE_SKIP_UPDATE_CHECK: "true"
        run: python3 smoke_testing/init.py ${PWD}/build/${{ matrix.os }}/kubescape
        